# Generated by Django 5.1.5 on 2025-02-22 17:42

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TOP', 'Top'), ('BOTTOM', 'Bottom'), ('OUTERWEAR', 'Outerwear'), ('DRESS', 'Dress'), ('SHOES', 'Shoes')])),
                ('subtype', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('T-SHIRT', 'T Shirt'), ('POLO', 'Polo'), ('BUTTON DOWN', 'Button Down'), ('HOODIE', 'Hoodie'), ('SWEATER', 'Sweater'), ('ACTIVE', 'Active'), ('JEANS', 'Jeans'), ('PANTS', 'Pants'), ('SHORTS', 'Shorts'), ('SKIRT', 'Skirt'), ('JACKET', 'Jacket'), ('COAT', 'Coat'), ('MINI', 'Mini'), ('MIDI', 'Midi'), ('MAXI', 'Maxi'), ('ACTIVE', 'Active'), ('SNEAKERS', 'Sneakers'), ('BOOTS', 'Boots'), ('SANDALS & SLIDES', 'Sandals Slides')], validators=[apps.core.models.Clothing.validate_subtype])),
                ('img_url', models.URLField()),
                ('color_lstar', models.FloatField()),
                ('color_astar', models.FloatField()),
                ('color_bstar', models.FloatField()),
                ('fit', models.CharField(choices=[('LOOSE', 'Loose'), ('FITTED', 'Fitted'), ('TIGHT', 'Tight')])),
                ('layerable', models.BooleanField(default=False)),
                ('precip', models.CharField(blank=True, choices=[('RAIN', 'Rain'), ('SNOW', 'Snow')])),
                ('occasion', models.CharField(choices=[('ACTIVE', 'Active'), ('CASUAL', 'Casual'), ('FORMAL', 'Formal')])),
                ('winter', models.BooleanField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_worn', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutfitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clothing')),
                ('outfit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.outfit')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True)),
                ('value', models.CharField()),
                ('clothing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clothing')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.AddField(
            model_name='clothing',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
    ]
