# Generated by Django 5.1.5 on 2025-04-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_outfit_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='winter',
        ),
        migrations.AddField(
            model_name='clothing',
            name='weather',
            field=models.CharField(choices=[('WINTER', 'Winter'), ('SUMMER', 'Summer')], default='SUMMER'),
        ),
    ]
