# Generated by Django 5.1.5 on 2025-04-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clothing_color_astar_2nd_clothing_color_bstar_2nd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
