# Generated by Django 5.1.5 on 2025-04-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_clothing_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='img_filename',
            field=models.URLField(blank=True, null=True),
        ),
    ]
