# Generated by Django 5.1.5 on 2025-04-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_outfit_img_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='weather',
            field=models.CharField(choices=[('WINTER', 'Winter'), ('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('FALL', 'Fall')], default='SUMMER'),
        ),
    ]
